export const POPULAR_COLORS = [
  { label: "Black", hex: "#000000" },
  { label: "White", hex: "#FFFFFF" },
  { label: "Grey", hex: "#808080" },
  { label: "Silver", hex: "#C0C0C0" },
  { label: "Brown", hex: "#8B4513" },
  { label: "Beige", hex: "#F5F5DC" },
  { label: "Red", hex: "#FF0000" },
  { label: "Maroon", hex: "#800000" },
  { label: "Pink", hex: "#FFC0CB" },
  { label: "Rose Gold", hex: "#B76E79" },
  { label: "Orange", hex: "#FFA500" },
  { label: "Yellow", hex: "#FFFF00" },
  { label: "Gold", hex: "#FFD700" },
  { label: "Green", hex: "#008000" },
  { label: "Olive", hex: "#808000" },
  { label: "Blue", hex: "#0000FF" },
  { label: "Navy", hex: "#000080" },
  { label: "Purple", hex: "#800080" },
  { label: "Multi", hex: "linear-gradient(45deg, red, blue, green, yellow)" },
];

export const ALL_COLORS = [
  ...POPULAR_COLORS,
  { label: "Alice Blue", hex: "#F0F8FF" },
  { label: "Antique White", hex: "#FAEBD7" },
  { label: "Aqua", hex: "#00FFFF" },
  { label: "Aquamarine", hex: "#7FFFD4" },
  { label: "Azure", hex: "#F0FFFF" },
  { label: "Beige", hex: "#F5F5DC" },
  { label: "Bisque", hex: "#FFE4C4" },
  { label: "Blanched Almond", hex: "#FFEBCD" },
  { label: "Blue Violet", hex: "#8A2BE2" },
  { label: "Brown", hex: "#A52A2A" },
  { label: "Burlywood", hex: "#DEB887" },
  { label: "Cadet Blue", hex: "#5F9EA0" },
  { label: "Chartreuse", hex: "#7FFF00" },
  { label: "Chocolate", hex: "#D2691E" },
  { label: "Coral", hex: "#FF7F50" },
  { label: "Cornflower Blue", hex: "#6495ED" },
  { label: "Cornsilk", hex: "#FFF8DC" },
  { label: "Crimson", hex: "#DC143C" },
  { label: "Cyan", hex: "#00FFFF" },
  { label: "Dark Blue", hex: "#00008B" },
  { label: "Dark Cyan", hex: "#008B8B" },
  { label: "Dark Goldenrod", hex: "#B8860B" },
  { label: "Dark Gray", hex: "#A9A9A9" },
  { label: "Dark Green", hex: "#006400" },
  { label: "Dark Khaki", hex: "#BDB76B" },
  { label: "Dark Magenta", hex: "#8B008B" },
  { label: "Dark Olive Green", hex: "#556B2F" },
  { label: "Dark Orange", hex: "#FF8C00" },
  { label: "Dark Orchid", hex: "#9932CC" },
  { label: "Dark Red", hex: "#8B0000" },
  { label: "Dark Salmon", hex: "#E9967A" },
  { label: "Dark Sea Green", hex: "#8FBC8F" },
  { label: "Dark Slate Blue", hex: "#483D8B" },
  { label: "Dark Slate Gray", hex: "#2F4F4F" },
  { label: "Dark Turquoise", hex: "#00CED1" },
  { label: "Dark Violet", hex: "#9400D3" },
  { label: "Deep Pink", hex: "#FF1493" },
  { label: "Deep Sky Blue", hex: "#00BFFF" },
  { label: "Dim Gray", hex: "#696969" },
  { label: "Dodger Blue", hex: "#1E90FF" },
  { label: "Firebrick", hex: "#B22222" },
  { label: "Floral White", hex: "#FFFAF0" },
  { label: "Forest Green", hex: "#228B22" },
  { label: "Fuchsia", hex: "#FF00FF" },
  { label: "Gainsboro", hex: "#DCDCDC" },
  { label: "Ghost White", hex: "#F8F8FF" },
  { label: "Goldenrod", hex: "#DAA520" },
  { label: "Green Yellow", hex: "#ADFF2F" },
  { label: "Honeydew", hex: "#F0FFF0" },
  { label: "Hot Pink", hex: "#FF69B4" },
  { label: "Indian Red", hex: "#CD5C5C" },
  { label: "Indigo", hex: "#4B0082" },
  { label: "Ivory", hex: "#FFFFF0" },
  { label: "Khaki", hex: "#F0E68C" },
  { label: "Lavender", hex: "#E6E6FA" },
  { label: "Lavender Blush", hex: "#FFF0F5" },
  { label: "Lawn Green", hex: "#7CFC00" },
  { label: "Lemon Chiffon", hex: "#FFFACD" },
  { label: "Light Blue", hex: "#ADD8E6" },
  { label: "Light Coral", hex: "#F08080" },
  { label: "Light Cyan", hex: "#E0FFFF" },
  { label: "Light Goldenrod Yellow", hex: "#FAFAD2" },
  { label: "Light Gray", hex: "#D3D3D3" },
  { label: "Light Green", hex: "#90EE90" },
  { label: "Light Pink", hex: "#FFB6C1" },
  { label: "Light Salmon", hex: "#FFA07A" },
  { label: "Light Sea Green", hex: "#20B2AA" },
  { label: "Light Sky Blue", hex: "#87CEFA" },
  { label: "Light Slate Gray", hex: "#778899" },
  { label: "Light Steel Blue", hex: "#B0C4DE" },
  { label: "Light Yellow", hex: "#FFFFE0" },
  { label: "Lime", hex: "#00FF00" },
  { label: "Lime Green", hex: "#32CD32" },
  { label: "Linen", hex: "#FAF0E6" },
  { label: "Magenta", hex: "#FF00FF" },
  { label: "Medium Aquamarine", hex: "#66CDAA" },
  { label: "Medium Blue", hex: "#0000CD" },
  { label: "Medium Orchid", hex: "#BA55D3" },
  { label: "Medium Purple", hex: "#9370DB" },
  { label: "Medium Sea Green", hex: "#3CB371" },
  { label: "Medium Slate Blue", hex: "#7B68EE" },
  { label: "Medium Spring Green", hex: "#00FA9A" },
  { label: "Medium Turquoise", hex: "#48D1CC" },
  { label: "Medium Violet Red", hex: "#C71585" },
  { label: "Midnight Blue", hex: "#191970" },
  { label: "Mint Cream", hex: "#F5FFFA" },
  { label: "Misty Rose", hex: "#FFE4E1" },
  { label: "Moccasin", hex: "#FFE4B5" },
  { label: "Navajo White", hex: "#FFDEAD" },
  { label: "Old Lace", hex: "#FDF5E6" },
  { label: "Olive Drab", hex: "#6B8E23" },
  { label: "Orange Red", hex: "#FF4500" },
  { label: "Orchid", hex: "#DA70D6" },
  { label: "Pale Goldenrod", hex: "#EEE8AA" },
  { label: "Pale Green", hex: "#98FB98" },
  { label: "Pale Turquoise", hex: "#AFEEEE" },
  { label: "Pale Violet Red", hex: "#DB7093" },
  { label: "Papaya Whip", hex: "#FFEFD5" },
  { label: "Peach Puff", hex: "#FFDAB9" },
  { label: "Peru", hex: "#CD853F" },
  { label: "Plum", hex: "#DDA0DD" },
  { label: "Powder Blue", hex: "#B0E0E6" },
  { label: "Rosy Brown", hex: "#BC8F8F" },
  { label: "Royal Blue", hex: "#4169E1" },
  { label: "Saddle Brown", hex: "#8B4513" },
  { label: "Salmon", hex: "#FA8072" },
  { label: "Sandy Brown", hex: "#F4A460" },
  { label: "Sea Green", hex: "#2E8B57" },
  { label: "Seashell", hex: "#FFF5EE" },
  { label: "Sienna", hex: "#A0522D" },
  { label: "Sky Blue", hex: "#87CEEB" },
  { label: "Slate Blue", hex: "#6A5ACD" },
  { label: "Slate Gray", hex: "#708090" },
  { label: "Snow", hex: "#FFFAFA" },
  { label: "Spring Green", hex: "#00FF7F" },
  { label: "Steel Blue", hex: "#4682B4" },
  { label: "Tan", hex: "#D2B48C" },
  { label: "Teal", hex: "#008080" },
  { label: "Thistle", hex: "#D8BFD8" },
  { label: "Tomato", hex: "#FF6347" },
  { label: "Turquoise", hex: "#40E0D0" },
  { label: "Violet", hex: "#EE82EE" },
  { label: "Wheat", hex: "#F5DEB3" },
  { label: "White Smoke", hex: "#F5F5F5" },
  { label: "Yellow Green", hex: "#9ACD32" }
].filter((v, i, a) => a.findIndex(t => (t.label === v.label)) === i); // Ensure unique labels
