ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "href" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "isVisible" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "storeType" TEXT NOT NULL DEFAULT 'STORE';
